# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-Postini
version:      0.01
version_from: lib/WWW/Postini.pm
installdirs:  site
requires:
    Crypt::SSLeay:                 0
    Exception::Class:              0
    Exporter:                      0
    HTML::TokeParser:              0
    HTTP::Cookies:                 0
    HTTP::Request:                 0
    HTTP::Status:                  0
    LWP::UserAgent:                0
    URI::Escape:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
